spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: facilit
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration

jwt:
  secret: "uma-chave-muito-secreta-e-comprida-32+_caracteres_para_desafio_estagio_facilit"
  expiration-ms: 3600000
